"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 10
palette = 'synthwave'

format = """
[┌─](bold green)$git_branch$git_status$git_commit
[│](bold green) $directory
[└─>](bold green) """

[palettes.synthwave]
blue    = '#00e5ff'
magenta = '#ff00ff'
mustard = '#af8700'

[character]
success_symbol = '[➜](bold green)'
error_symbol   = '[✗](bold red)'

[directory]
truncation_length = 4
truncate_to_repo  = true

[git_branch]
symbol           = ''
truncation_length = 20
truncation_symbol = '…'
ignore_branches  = []
format           = 'on [⎇  $branch$truncation_symbol](bold purple) '

[git_commit]
commit_hash_length = 4
tag_symbol         = '🔖 '

[git_status]
conflicted = '=$count'
up_to_date = ''
untracked  = '?$count'
stashed    = 'stash'
modified   = '!$count'
staged     = '+$count'
renamed    = 'r$count'
deleted    = 'd$count'
ahead      = '⇡$count'
diverged   = '⇡$ahead_count⇣$behind_count'
behind     = '⇣$count'
format     = '([\[$all_status$ahead_behind\]](yellow) )'

[rust]
format = 'via [⚙️  $version](red bold) '

[dart]
format = 'via [🔰 $version](bold red) '

[nodejs]
format = 'via [🤖 $version](bold green) '

[username]
style_user  = 'white bold'
style_root  = 'black bold'
format      = '[$user]($style) '
disabled    = false
show_always = false

[sudo]
style    = 'bold green'
symbol   = '👩‍💻 '
disabled = false

[battery]
full_symbol        = '🔋 '
charging_symbol    = '⚡️ '
discharging_symbol = '💀 '

[[battery.display]]
threshold = 30
style     = 'bold red'

[cmd_duration]
min_time = 2_000
format   = 'took [$duration](bold yellow) '

[package]
disabled = true

[os]
disabled = false

[os.symbols]
Android = "🤖 "
Arch    = "🎗️ "
Windows = "🪟 "
