shell /usr/bin/fish
font_family JetBrainsMono Nerd Font
font_size 14.0

# Colors - Synthwave '84 Vibes
foreground #f1f1f1
background #1a1b26
selection_foreground #000000
selection_background #ff79c6
cursor #ff79c6

# Color palette
color0  #1a1b26
color1  #ff6e96
color2 #fffb00
color3  #f1fa8c
color4  #bd93f9
color5  #ff79c6
color6  #8be9fd
color7  #f8f8f2
color8  #6272a4
color9  #ff6e96
color10 #50fa7b
color11 #f1fa8c
color12 #bd93f9
color13 #ff79c6
color14 #8be9fd
color15 #ffffff

# Transparency
background_opacity 0.7

# Padding and tweaks
window_padding_width 8
cursor_shape beam
enable_audio_bell no
tab_bar_edge top
